import { BotConfig, ApiProfile, SlashCommand, BotDeploymentType, AuthType, ResponseType } from './types';

/**
 * ボットテンプレートの型定義
 */
export interface BotTemplate {
  id: string;
  name: string;
  description: string;
  category: 'utility' | 'fun' | 'moderation' | 'api-integration' | 'custom';
  icon?: string; // 絵文字またはアイコン名
  thumbnail?: string; // サムネイル画像URL
  defaultBotConfig: Partial<BotConfig>;
  apiProfiles: ApiProfile[];
  commands: Omit<SlashCommand, 'id'>[];
  tags: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

/**
 * 利用可能なボットテンプレート一覧
 */
export const BOT_TEMPLATES: BotTemplate[] = [
  // 1. シンプルな挨拶ボット（初心者向け）
  {
    id: 'simple-greeting',
    name: '挨拶ボット',
    description: 'シンプルな挨拶コマンドを持つボット。Discord Botの基本を学ぶのに最適です。',
    category: 'fun',
    icon: '👋',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'シンプルな挨拶ボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'hello',
        description: '挨拶をします',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'こんにちは！👋 私は挨拶ボットです！',
        autoGeneratedCode: true,
      },
      {
        name: 'ping',
        description: 'Pong!と返します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'Pong! 🏓',
        autoGeneratedCode: true,
      },
      {
        name: 'greet',
        description: '指定したユーザーに挨拶します',
        options: [
          {
            name: 'user',
            description: '挨拶するユーザー',
            type: 'user',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'こんにちは、{user}さん！ 👋',
        autoGeneratedCode: true,
      },
    ],
    tags: ['初心者', '挨拶', 'シンプル'],
    difficulty: 'beginner',
  },

  // 2. サーバー情報ボット（中級者向け）
  {
    id: 'server-info',
    name: 'サーバー管理ボット',
    description: 'サーバーやユーザーの情報を表示する管理用ボット。Discord APIの使い方を学べます。',
    category: 'utility',
    icon: '📊',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'サーバー情報表示ボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'serverinfo',
        description: 'サーバーの情報を表示します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '📊 サーバー情報\n\nこのコマンドは実装中です。Discord APIを使用してサーバー情報を取得できます。',
        autoGeneratedCode: true,
      },
      {
        name: 'userinfo',
        description: 'ユーザーの情報を表示します',
        options: [
          {
            name: 'user',
            description: '情報を表示するユーザー',
            type: 'user',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '👤 ユーザー情報: {user}\n\nこのコマンドは実装中です。Discord APIを使用してユーザー情報を取得できます。',
        autoGeneratedCode: true,
      },
      {
        name: 'membercount',
        description: 'サーバーのメンバー数を表示します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '👥 このサーバーには多くのメンバーがいます！',
        autoGeneratedCode: true,
      },
    ],
    tags: ['管理', '情報', 'サーバー'],
    difficulty: 'intermediate',
  },

  // 3. 天気情報ボット（API連携）
  {
    id: 'weather-bot',
    name: '天気情報ボット',
    description: 'OpenWeatherMap APIを使用して天気情報を提供するボット。外部API連携の基本を学べます。',
    category: 'api-integration',
    icon: '🌤️',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: '天気情報提供ボット',
    },
    apiProfiles: [
      {
        id: 'openweathermap',
        name: 'OpenWeatherMap',
        baseUrl: 'https://api.openweathermap.org/data/2.5',
        authType: 'API_KEY_QUERY' as AuthType,
        apiKeyName: 'appid',
        envVarKey: 'OPENWEATHERMAP_API_KEY',
        envVarUrl: 'OPENWEATHERMAP_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'weather',
        description: '指定した都市の天気を取得します',
        options: [
          {
            name: 'city',
            description: '都市名（例: Tokyo, Osaka）',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'openweathermap',
        apiEndpoint: '/weather?q={city}&units=metric&lang=ja',
        fieldMappings: [
          {
            fieldPath: 'name',
            displayLabel: '都市',
            formatString: '{name}',
          },
          {
            fieldPath: 'weather.0.description',
            displayLabel: '天気',
            formatString: '{weather.0.description}',
          },
          {
            fieldPath: 'main.temp',
            displayLabel: '気温',
            formatString: '{main.temp}°C',
          },
          {
            fieldPath: 'main.humidity',
            displayLabel: '湿度',
            formatString: '{main.humidity}%',
          },
        ],
        autoGeneratedCode: true,
      },
      {
        name: 'forecast',
        description: '指定した都市の5日間の天気予報を取得します',
        options: [
          {
            name: 'city',
            description: '都市名（例: Tokyo, Osaka）',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'openweathermap',
        apiEndpoint: '/forecast?q={city}&units=metric&lang=ja&cnt=5',
        autoGeneratedCode: true,
      },
    ],
    tags: ['天気', 'API連携', '外部API'],
    difficulty: 'intermediate',
  },

  // 4. FAQ/ヘルプボット
  {
    id: 'faq-bot',
    name: 'FAQ/ヘルプボット',
    description: 'よくある質問に自動で答えるボット。コミュニティサポートに便利です。',
    category: 'utility',
    icon: '❓',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'FAQ自動応答ボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'faq',
        description: 'よくある質問を表示します',
        options: [
          {
            name: 'category',
            description: 'カテゴリを選択',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '📚 よくある質問\n\nカテゴリ: {category}\n\nここに回答が表示されます。',
        autoGeneratedCode: true,
      },
      {
        name: 'help',
        description: 'ボットの使い方を表示します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '📖 ヘルプ\n\n利用可能なコマンド:\n• /faq - よくある質問を表示\n• /help - このヘルプを表示\n• /contact - サポートへの連絡方法',
        autoGeneratedCode: true,
      },
      {
        name: 'contact',
        description: 'サポートへの連絡方法を表示します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '📧 お問い合わせ\n\nサポートが必要な場合は、サーバーの管理者にお問い合わせください。',
        autoGeneratedCode: true,
      },
    ],
    tags: ['FAQ', 'ヘルプ', 'サポート'],
    difficulty: 'beginner',
  },

  // 5. ゲーム/エンターテイメントボット
  {
    id: 'fun-games',
    name: 'ゲームボット',
    description: 'サイコロやじゃんけんなどのミニゲームで遊べるボット。',
    category: 'fun',
    icon: '🎮',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'ゲーム・エンターテイメントボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'dice',
        description: 'サイコロを振ります',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🎲 サイコロの結果: {random(1, 6)}',
        autoGeneratedCode: true,
      },
      {
        name: 'coinflip',
        description: 'コインを投げます',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🪙 結果: {random("表", "裏")}',
        autoGeneratedCode: true,
      },
      {
        name: 'rps',
        description: 'じゃんけんをします',
        options: [
          {
            name: 'choice',
            description: 'グー、チョキ、パーから選択',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'あなた: {choice}\nボット: {random("グー", "チョキ", "パー")}\n\n結果は...？',
        autoGeneratedCode: true,
      },
    ],
    tags: ['ゲーム', '娯楽', 'ランダム'],
    difficulty: 'beginner',
  },

  // 6. リマインダー/タスク管理ボット
  {
    id: 'reminder-bot',
    name: 'リマインダーボット',
    description: 'タスク管理やリマインダー機能を持つボット（基本テンプレート）。',
    category: 'utility',
    icon: '⏰',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'リマインダー・タスク管理ボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'remind',
        description: 'リマインダーを設定します（基本版）',
        options: [
          {
            name: 'message',
            description: 'リマインドする内容',
            type: 'string',
            required: true,
          },
          {
            name: 'time',
            description: '時間（例: 1h, 30m）',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '⏰ リマインダーを設定しました！\n\n内容: {message}\n時間: {time}\n\n※この機能を完全に実装するには、データベースとスケジューラーが必要です。',
        autoGeneratedCode: true,
      },
      {
        name: 'todo',
        description: 'TODOリストに追加します',
        options: [
          {
            name: 'task',
            description: 'タスクの内容',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '✅ タスクを追加しました: {task}\n\n※この機能を完全に実装するには、データベースが必要です。',
        autoGeneratedCode: true,
      },
    ],
    tags: ['リマインダー', 'タスク管理', '生産性'],
    difficulty: 'intermediate',
  },

  // 7. 引用/名言ボット（外部API）
  {
    id: 'quote-bot',
    name: '名言ボット',
    description: 'ランダムな名言や引用を表示するボット。',
    category: 'fun',
    icon: '💭',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: '名言・引用ボット',
    },
    apiProfiles: [
      {
        id: 'quotable',
        name: 'Quotable API',
        baseUrl: 'https://api.quotable.io',
        authType: 'NONE' as AuthType,
        envVarKey: '',
        envVarUrl: 'QUOTABLE_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'quote',
        description: 'ランダムな名言を表示します',
        options: [],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'quotable',
        apiEndpoint: '/random',
        fieldMappings: [
          {
            fieldPath: 'content',
            displayLabel: '名言',
            formatString: '"{content}"',
          },
          {
            fieldPath: 'author',
            displayLabel: '著者',
            formatString: '— {author}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['名言', '引用', 'インスピレーション'],
    difficulty: 'beginner',
  },

  // 8. 空のテンプレート（カスタム用）
  {
    id: 'blank',
    name: '空のテンプレート',
    description: 'ゼロから自分でボットを作成します。完全にカスタマイズ可能です。',
    category: 'custom',
    icon: '📝',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: '',
    },
    apiProfiles: [],
    commands: [],
    tags: ['カスタム', '空', '自由'],
    difficulty: 'beginner',
  },
];

/**
 * テンプレートIDからテンプレートを取得
 */
export function getTemplateById(id: string): BotTemplate | undefined {
  return BOT_TEMPLATES.find(template => template.id === id);
}

/**
 * カテゴリでテンプレートをフィルタリング
 */
export function getTemplatesByCategory(category: BotTemplate['category']): BotTemplate[] {
  return BOT_TEMPLATES.filter(template => template.category === category);
}

/**
 * 難易度でテンプレートをフィルタリング
 */
export function getTemplatesByDifficulty(difficulty: BotTemplate['difficulty']): BotTemplate[] {
  return BOT_TEMPLATES.filter(template => template.difficulty === difficulty);
}

/**
 * テンプレートからプロジェクト設定を生成
 */
export function createProjectConfigFromTemplate(
  template: BotTemplate,
  overrides: {
    repositoryName: string;
    botName: string;
    userId: string;
    repositoryDescription?: string;
    isPrivate?: boolean;
  }
) {
  // コマンドにIDを付与
  const commandsWithIds = template.commands.map((cmd, index) => ({
    ...cmd,
    id: `${template.id}-cmd-${index}`,
  }));

  return {
    repository: {
      name: overrides.repositoryName,
      branch: 'main',
      description: overrides.repositoryDescription || template.description,
      isPrivate: overrides.isPrivate ?? true,
    },
    botConfig: {
      name: overrides.botName,
      description: template.defaultBotConfig.description || template.description,
      deploymentType: template.defaultBotConfig.deploymentType || ('INTERACTIONS_ENDPOINT' as BotDeploymentType),
    },
    apiProfiles: template.apiProfiles,
    commands: commandsWithIds,
  };
}
