import { BotConfig, ApiProfile, SlashCommand, BotDeploymentType, AuthType, ResponseType } from './types';

/**
 * ボットテンプレートの型定義
 */
export interface BotTemplate {
  id: string;
  name: string;
  description: string;
  category: 'utility' | 'fun' | 'info' | 'custom';
  icon?: string;
  thumbnail?: string;
  defaultBotConfig: Partial<BotConfig>;
  apiProfiles: ApiProfile[];
  commands: Omit<SlashCommand, 'id'>[];
  tags: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  setupInstructions?: string; // APIキーの取得方法など
}

/**
 * 利用可能なボットテンプレート一覧
 * 全て無料のOSS APIを使用し、設定済みで「次へ」を押すだけで完成
 */
export const BOT_TEMPLATES: BotTemplate[] = [
  // 1. 犬の画像ボット（API認証不要）
  {
    id: 'dog-images',
    name: '🐕 犬の画像ボット',
    description: 'ランダムな犬の画像や犬種別の画像を表示するボット。API設定不要で即使用可能！',
    category: 'fun',
    icon: '🐕',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'かわいい犬の画像を表示するボット',
    },
    apiProfiles: [
      {
        id: 'dog-api',
        name: 'Dog API',
        baseUrl: 'https://dog.ceo/api',
        authType: 'NONE' as AuthType,
        envVarKey: '',
        envVarUrl: 'DOG_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'randomdog',
        description: 'ランダムな犬の画像を表示します',
        options: [],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'dog-api',
        apiEndpoint: '/breeds/image/random',
        fieldMappings: [
          {
            fieldPath: 'message',
            displayLabel: '犬の画像',
            formatString: '🐕 かわいい犬の画像だよ！\n{message}',
          },
        ],
        autoGeneratedCode: true,
      },
      {
        name: 'dogbreeds',
        description: '全ての犬種リストを表示します',
        options: [],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'dog-api',
        apiEndpoint: '/breeds/list/all',
        fieldMappings: [
          {
            fieldPath: 'status',
            displayLabel: 'ステータス',
            formatString: '犬種リストを取得しました！（ステータス: {status}）',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['犬', '画像', 'API不要', '即利用可能'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 2. 猫の画像ボット（API認証不要）
  {
    id: 'cat-images',
    name: '🐱 猫の画像ボット',
    description: 'ランダムな猫の画像を表示するボット。API設定不要で即使用可能！',
    category: 'fun',
    icon: '🐱',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'かわいい猫の画像を表示するボット',
    },
    apiProfiles: [
      {
        id: 'cataas-api',
        name: 'Cat as a Service',
        baseUrl: 'https://cataas.com',
        authType: 'NONE' as AuthType,
        envVarKey: '',
        envVarUrl: 'CATAAS_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'randomcat',
        description: 'ランダムな猫の画像を表示します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🐱 かわいい猫の画像だよ！\nhttps://cataas.com/cat',
        autoGeneratedCode: true,
      },
      {
        name: 'catgif',
        description: '猫のGIFを表示します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🐱 猫のGIFだよ！\nhttps://cataas.com/cat/gif',
        autoGeneratedCode: true,
      },
      {
        name: 'catsays',
        description: '猫に好きなメッセージを言わせます',
        options: [
          {
            name: 'text',
            description: '猫に言わせたいメッセージ',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🐱 猫が "{text}" って言ってるよ！\nhttps://cataas.com/cat/says/{text}',
        autoGeneratedCode: true,
      },
    ],
    tags: ['猫', '画像', 'GIF', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 3. ジョークボット（API認証不要）
  {
    id: 'joke-bot',
    name: '😂 ジョークボット',
    description: 'プログラミングジョークやランダムなジョークを提供するボット。API設定不要！',
    category: 'fun',
    icon: '😂',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'ジョークでみんなを笑顔にするボット',
    },
    apiProfiles: [
      {
        id: 'jokeapi',
        name: 'JokeAPI',
        baseUrl: 'https://v2.jokeapi.dev',
        authType: 'NONE' as AuthType,
        envVarKey: '',
        envVarUrl: 'JOKEAPI_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'joke',
        description: 'ランダムなジョークを表示します',
        options: [],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'jokeapi',
        apiEndpoint: '/joke/Any?safe-mode',
        fieldMappings: [
          {
            fieldPath: 'joke',
            displayLabel: 'ジョーク',
            formatString: '😂 {joke}',
          },
          {
            fieldPath: 'setup',
            displayLabel: 'セットアップ',
            formatString: '😂 {setup}\n💡 {delivery}',
          },
        ],
        autoGeneratedCode: true,
      },
      {
        name: 'progjoke',
        description: 'プログラミング関連のジョークを表示します',
        options: [],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'jokeapi',
        apiEndpoint: '/joke/Programming?safe-mode',
        fieldMappings: [
          {
            fieldPath: 'joke',
            displayLabel: 'ジョーク',
            formatString: '💻😂 {joke}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['ジョーク', '面白い', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 4. アドバイスボット（API認証不要）
  {
    id: 'advice-bot',
    name: '💡 アドバイスボット',
    description: 'ランダムなアドバイスを提供するボット。人生のヒントが欲しい時に！',
    category: 'info',
    icon: '💡',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'ランダムなアドバイスを提供するボット',
    },
    apiProfiles: [
      {
        id: 'adviceslip',
        name: 'Advice Slip API',
        baseUrl: 'https://api.adviceslip.com',
        authType: 'NONE' as AuthType,
        envVarKey: '',
        envVarUrl: 'ADVICESLIP_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'advice',
        description: 'ランダムなアドバイスを取得します',
        options: [],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'adviceslip',
        apiEndpoint: '/advice',
        fieldMappings: [
          {
            fieldPath: 'slip.advice',
            displayLabel: 'アドバイス',
            formatString: '💡 **今日のアドバイス**\n{slip.advice}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['アドバイス', '名言', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 5. 数字の豆知識ボット（API認証不要）
  {
    id: 'numbers-trivia',
    name: '🔢 数字トリビアボット',
    description: '数字に関する面白い豆知識を教えてくれるボット。',
    category: 'info',
    icon: '🔢',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: '数字の豆知識を教えてくれるボット',
    },
    apiProfiles: [
      {
        id: 'numbersapi',
        name: 'Numbers API',
        baseUrl: 'http://numbersapi.com',
        authType: 'NONE' as AuthType,
        envVarKey: '',
        envVarUrl: 'NUMBERSAPI_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'numfact',
        description: '指定した数字の豆知識を取得します',
        options: [
          {
            name: 'number',
            description: '豆知識を知りたい数字',
            type: 'integer',
            required: true,
          },
        ],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'numbersapi',
        apiEndpoint: '/{number}',
        autoGeneratedCode: true,
      },
      {
        name: 'randomnumber',
        description: 'ランダムな数字の豆知識を取得します',
        options: [],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'numbersapi',
        apiEndpoint: '/random',
        autoGeneratedCode: true,
      },
    ],
    tags: ['数字', '豆知識', 'トリビア', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 6. GitHubユーザー情報ボット（API認証不要）
  {
    id: 'github-info',
    name: '🐙 GitHub情報ボット',
    description: 'GitHubユーザーやリポジトリの情報を取得するボット。',
    category: 'info',
    icon: '🐙',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'GitHub情報を取得するボット',
    },
    apiProfiles: [
      {
        id: 'github-api',
        name: 'GitHub API',
        baseUrl: 'https://api.github.com',
        authType: 'NONE' as AuthType,
        envVarKey: '',
        envVarUrl: 'GITHUB_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'githubuser',
        description: 'GitHubユーザーの情報を取得します',
        options: [
          {
            name: 'username',
            description: 'GitHubユーザー名',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'API_CALL' as ResponseType,
        apiProfileId: 'github-api',
        apiEndpoint: '/users/{username}',
        fieldMappings: [
          {
            fieldPath: 'login',
            displayLabel: 'ユーザー名',
            formatString: '🐙 **{login}**',
          },
          {
            fieldPath: 'name',
            displayLabel: '名前',
            formatString: '名前: {name}',
          },
          {
            fieldPath: 'bio',
            displayLabel: 'バイオ',
            formatString: 'バイオ: {bio}',
          },
          {
            fieldPath: 'public_repos',
            displayLabel: 'リポジトリ数',
            formatString: 'リポジトリ: {public_repos}個',
          },
          {
            fieldPath: 'followers',
            displayLabel: 'フォロワー',
            formatString: 'フォロワー: {followers}人',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['GitHub', '開発者', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。\nレート制限: 1時間あたり60リクエスト',
  },

  // 7. ゲームボット（API不要）
  {
    id: 'fun-games',
    name: '🎮 ゲームボット',
    description: 'サイコロ、コイントス、じゃんけんなどのミニゲーム。API不要！',
    category: 'fun',
    icon: '🎮',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'ゲーム・エンターテイメントボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'dice',
        description: 'サイコロを振ります（1〜6）',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🎲 サイコロの結果: {random(1, 6)}',
        autoGeneratedCode: true,
      },
      {
        name: 'coinflip',
        description: 'コインを投げます',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🪙 結果: {random("表", "裏")}',
        autoGeneratedCode: true,
      },
      {
        name: 'rps',
        description: 'じゃんけんをします',
        options: [
          {
            name: 'choice',
            description: 'グー、チョキ、パーから選択',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'あなた: {choice}\nボット: {random("グー", "チョキ", "パー")}\n\n結果は...？',
        autoGeneratedCode: true,
      },
      {
        name: '8ball',
        description: 'マジック8ボール（質問に答えます）',
        options: [
          {
            name: 'question',
            description: 'Yes/Noで答えられる質問',
            type: 'string',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: '🎱 質問: {question}\n\n答え: {random("はい、間違いありません", "確実です", "間違いなくそうです", "多分そうでしょう", "見込みあり", "微妙です", "もう一度聞いて", "今は答えられません", "見通しは良くない", "非常に疑わしい")}',
        autoGeneratedCode: true,
      },
    ],
    tags: ['ゲーム', '娯楽', 'API不要', 'ランダム'],
    difficulty: 'beginner',
    setupInstructions: 'API不要！完全にローカルで動作します。',
  },

  // 8. 挨拶ボット（API不要、シンプル）
  {
    id: 'simple-greeting',
    name: '👋 シンプル挨拶ボット',
    description: '基本的な挨拶コマンド。Discord Botの基礎を学ぶのに最適。',
    category: 'utility',
    icon: '👋',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: 'シンプルな挨拶ボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'hello',
        description: '挨拶をします',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'こんにちは！👋 私はDiscord Botです！',
        autoGeneratedCode: true,
      },
      {
        name: 'ping',
        description: 'Pong!と返します',
        options: [],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'Pong! 🏓',
        autoGeneratedCode: true,
      },
      {
        name: 'greet',
        description: '指定したユーザーに挨拶します',
        options: [
          {
            name: 'user',
            description: '挨拶するユーザー',
            type: 'user',
            required: true,
          },
        ],
        responseType: 'STATIC_TEXT' as ResponseType,
        staticText: 'こんにちは、{user}さん！ 👋',
        autoGeneratedCode: true,
      },
    ],
    tags: ['初心者', '挨拶', 'シンプル', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'API不要！Discord Botの基本を学べる最もシンプルなテンプレートです。',
  },

  // 9. 空のテンプレート（カスタム用）
  {
    id: 'blank',
    name: '📝 空のテンプレート',
    description: 'ゼロから自分でボットを作成します。完全にカスタマイズ可能です。',
    category: 'custom',
    icon: '📝',
    defaultBotConfig: {
      deploymentType: 'INTERACTIONS_ENDPOINT' as BotDeploymentType,
      description: '',
    },
    apiProfiles: [],
    commands: [],
    tags: ['カスタム', '空', '自由'],
    difficulty: 'beginner',
    setupInstructions: '自由にコマンドとAPIを追加してください。',
  },
];

/**
 * テンプレートIDからテンプレートを取得
 */
export function getTemplateById(id: string): BotTemplate | undefined {
  return BOT_TEMPLATES.find(template => template.id === id);
}

/**
 * カテゴリでテンプレートをフィルタリング
 */
export function getTemplatesByCategory(category: BotTemplate['category']): BotTemplate[] {
  return BOT_TEMPLATES.filter(template => template.category === category);
}

/**
 * 難易度でテンプレートをフィルタリング
 */
export function getTemplatesByDifficulty(difficulty: BotTemplate['difficulty']): BotTemplate[] {
  return BOT_TEMPLATES.filter(template => template.difficulty === difficulty);
}

/**
 * テンプレートからプロジェクト設定を生成
 */
export function createProjectConfigFromTemplate(
  template: BotTemplate,
  overrides: {
    repositoryName: string;
    botName: string;
    userId: string;
    repositoryDescription?: string;
    isPrivate?: boolean;
  }
) {
  // コマンドにIDを付与
  const commandsWithIds = template.commands.map((cmd, index) => ({
    ...cmd,
    id: `${template.id}-cmd-${index}`,
  }));

  return {
    repository: {
      name: overrides.repositoryName,
      branch: 'main',
      description: overrides.repositoryDescription || template.description,
      isPrivate: overrides.isPrivate ?? true,
    },
    botConfig: {
      name: overrides.botName,
      description: template.defaultBotConfig.description || template.description,
      deploymentType: template.defaultBotConfig.deploymentType || ('INTERACTIONS_ENDPOINT' as BotDeploymentType),
    },
    apiProfiles: template.apiProfiles,
    commands: commandsWithIds,
  };
}
