import { BotConfig, ApiProfile, SlashCommand, BotDeploymentType, AuthType, ResponseType } from './types';

/**
 * ボットテンプレートの型定義
 */
export interface BotTemplate {
  id: string;
  name: string;
  description: string;
  category: 'utility' | 'fun' | 'info' | 'custom';
  icon?: string;
  thumbnail?: string;
  defaultBotConfig: Partial<BotConfig>;
  apiProfiles: ApiProfile[];
  commands: Omit<SlashCommand, 'id'>[];
  tags: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  setupInstructions?: string; // APIキーの取得方法など
}

/**
 * 利用可能なボットテンプレート一覧
 * 全て無料のOSS APIを使用し、設定済みで「次へ」を押すだけで完成
 */
export const BOT_TEMPLATES: BotTemplate[] = [
  // 1. 犬の画像ボット（API認証不要）
  {
    id: 'dog-images',
    name: '🐕 犬の画像ボット',
    description: 'ランダムな犬の画像を表示するボット。API設定不要で即使用可能！',
    category: 'fun',
    icon: '🐕',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'かわいい犬の画像を表示するボット',
    },
    apiProfiles: [
      {
        id: 'dog-api',
        name: 'Random Dog API',
        baseUrl: 'https://random.dog',
        authType: AuthType.NONE,
        envVarKey: '',
        envVarUrl: 'DOG_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'randomdog',
        description: 'ランダムな犬の画像を表示します',
        options: [],
        responseType: ResponseType.API_CALL,
        apiProfileId: 'dog-api',
        apiEndpoint: '/woof.json',
        fieldMappings: [
          {
            fieldPath: 'url',
            displayLabel: '犬の画像',
            formatString: '🐕 かわいい犬の画像だよ！\n{url}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['犬', '画像', 'API不要', '即利用可能'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 2. 猫の画像ボット（API認証不要）
  {
    id: 'cat-images',
    name: '🐱 猫の画像ボット',
    description: 'ランダムな猫の画像を表示するボット。API設定不要で即使用可能！',
    category: 'fun',
    icon: '🐱',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'かわいい猫の画像を表示するボット',
    },
    apiProfiles: [
      {
        id: 'cat-api',
        name: 'Random Cat API',
        baseUrl: 'https://aws.random.cat',
        authType: AuthType.NONE,
        envVarKey: '',
        envVarUrl: 'CAT_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'randomcat',
        description: 'ランダムな猫の画像を表示します',
        options: [],
        responseType: ResponseType.API_CALL,
        apiProfileId: 'cat-api',
        apiEndpoint: '/meow',
        fieldMappings: [
          {
            fieldPath: 'file',
            displayLabel: '猫の画像',
            formatString: '🐱 かわいい猫の画像だよ！\n{file}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['猫', '画像', 'API不要', '即利用可能'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 3. ジョークボット（API認証不要）
  {
    id: 'joke-bot',
    name: '😂 ジョークボット',
    description: 'ランダムなジョークを提供するボット。API設定不要！',
    category: 'fun',
    icon: '😂',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'ジョークでみんなを笑顔にするボット',
    },
    apiProfiles: [
      {
        id: 'joke-api',
        name: 'Official Joke API',
        baseUrl: 'https://official-joke-api.appspot.com',
        authType: AuthType.NONE,
        envVarKey: '',
        envVarUrl: 'JOKE_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'joke',
        description: 'ランダムなジョークを表示します',
        options: [],
        responseType: ResponseType.API_CALL,
        apiProfileId: 'joke-api',
        apiEndpoint: '/jokes/random',
        fieldMappings: [
          {
            fieldPath: 'setup',
            displayLabel: 'セットアップ',
            formatString: '😂 {setup}',
          },
          {
            fieldPath: 'punchline',
            displayLabel: 'オチ',
            formatString: '💡 {punchline}',
          },
        ],
        autoGeneratedCode: true,
      },
      {
        name: 'progjoke',
        description: 'プログラミング関連のジョークを表示します',
        options: [],
        responseType: ResponseType.API_CALL,
        apiProfileId: 'joke-api',
        apiEndpoint: '/jokes/programming/random',
        fieldMappings: [
          {
            fieldPath: 'setup',
            displayLabel: 'セットアップ',
            formatString: '💻😂 {setup}',
          },
          {
            fieldPath: 'punchline',
            displayLabel: 'オチ',
            formatString: '💡 {punchline}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['ジョーク', '面白い', 'API不要', '即利用可能'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 4. 名言ボット（API認証不要）
  {
    id: 'quote-bot',
    name: '💡 名言ボット',
    description: 'ランダムな名言を提供するボット。人生のヒントが欲しい時に！',
    category: 'info',
    icon: '💡',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'ランダムな名言を提供するボット',
    },
    apiProfiles: [
      {
        id: 'quotable-api',
        name: 'Quotable API',
        baseUrl: 'https://api.quotable.io',
        authType: AuthType.NONE,
        envVarKey: '',
        envVarUrl: 'QUOTABLE_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'quote',
        description: 'ランダムな名言を取得します',
        options: [],
        responseType: ResponseType.API_CALL,
        apiProfileId: 'quotable-api',
        apiEndpoint: '/random',
        fieldMappings: [
          {
            fieldPath: 'content',
            displayLabel: '名言',
            formatString: '💡 **今日の名言**\n"{content}"',
          },
          {
            fieldPath: 'author',
            displayLabel: '著者',
            formatString: '— {author}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['名言', '格言', 'API不要', '即利用可能'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 5. トリビアクイズボット（API認証不要）
  {
    id: 'trivia-quiz',
    name: '❓ トリビアクイズボット',
    description: 'ランダムなトリビアクイズを出題するボット。知識を試そう！',
    category: 'fun',
    icon: '❓',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'トリビアクイズを出題するボット',
    },
    apiProfiles: [
      {
        id: 'trivia-api',
        name: 'Open Trivia Database',
        baseUrl: 'https://opentdb.com',
        authType: AuthType.NONE,
        envVarKey: '',
        envVarUrl: 'TRIVIA_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'trivia',
        description: 'ランダムなトリビアクイズを取得します',
        options: [],
        responseType: ResponseType.API_CALL,
        apiProfileId: 'trivia-api',
        apiEndpoint: '/api.php?amount=1',
        fieldMappings: [
          {
            fieldPath: 'results.0.category',
            displayLabel: 'カテゴリ',
            formatString: '❓ **カテゴリ**: {results.0.category}',
          },
          {
            fieldPath: 'results.0.difficulty',
            displayLabel: '難易度',
            formatString: '📊 **難易度**: {results.0.difficulty}',
          },
          {
            fieldPath: 'results.0.question',
            displayLabel: '問題',
            formatString: '❔ **問題**: {results.0.question}',
          },
          {
            fieldPath: 'results.0.correct_answer',
            displayLabel: '正解',
            formatString: '✅ **正解**: {results.0.correct_answer}',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['クイズ', 'トリビア', '知識', 'API不要', '即利用可能'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。',
  },

  // 6. GitHubユーザー情報ボット（API認証不要）
  {
    id: 'github-info',
    name: '🐙 GitHub情報ボット',
    description: 'GitHubユーザーやリポジトリの情報を取得するボット。',
    category: 'info',
    icon: '🐙',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'GitHub情報を取得するボット',
    },
    apiProfiles: [
      {
        id: 'github-api',
        name: 'GitHub API',
        baseUrl: 'https://api.github.com',
        authType: AuthType.NONE,
        envVarKey: '',
        envVarUrl: 'GITHUB_API_BASE_URL',
      },
    ],
    commands: [
      {
        name: 'githubuser',
        description: 'GitHubユーザーの情報を取得します',
        options: [
          {
            name: 'username',
            description: 'GitHubユーザー名',
            type: 'string',
            required: true,
          },
        ],
        responseType: ResponseType.API_CALL,
        apiProfileId: 'github-api',
        apiEndpoint: '/users/{username}',
        fieldMappings: [
          {
            fieldPath: 'login',
            displayLabel: 'ユーザー名',
            formatString: '🐙 **{login}**',
          },
          {
            fieldPath: 'name',
            displayLabel: '名前',
            formatString: '名前: {name}',
          },
          {
            fieldPath: 'bio',
            displayLabel: 'バイオ',
            formatString: 'バイオ: {bio}',
          },
          {
            fieldPath: 'public_repos',
            displayLabel: 'リポジトリ数',
            formatString: 'リポジトリ: {public_repos}個',
          },
          {
            fieldPath: 'followers',
            displayLabel: 'フォロワー',
            formatString: 'フォロワー: {followers}人',
          },
        ],
        autoGeneratedCode: true,
      },
    ],
    tags: ['GitHub', '開発者', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'APIキー不要！テンプレートを選んで「次へ」を押すだけで使えます。\nレート制限: 1時間あたり60リクエスト',
  },

  // 7. ゲームボット（API不要）
  {
    id: 'fun-games',
    name: '🎮 ゲームボット',
    description: 'サイコロ、コイントス、じゃんけんなどのミニゲーム。API不要！',
    category: 'fun',
    icon: '🎮',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'ゲーム・エンターテイメントボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'dice',
        description: 'サイコロを振ります（1〜6）',
        options: [],
        responseType: ResponseType.STATIC_TEXT,
        staticText: '🎲 サイコロの結果: {random(1, 6)}',
        autoGeneratedCode: true,
      },
      {
        name: 'coinflip',
        description: 'コインを投げます',
        options: [],
        responseType: ResponseType.STATIC_TEXT,
        staticText: '🪙 結果: {random("表", "裏")}',
        autoGeneratedCode: true,
      },
      {
        name: 'rps',
        description: 'じゃんけんをします',
        options: [
          {
            name: 'choice',
            description: 'グー、チョキ、パーから選択',
            type: 'string',
            required: true,
          },
        ],
        responseType: ResponseType.STATIC_TEXT,
        staticText: 'あなた: {choice}\nボット: {random("グー", "チョキ", "パー")}\n\n結果は...？',
        autoGeneratedCode: true,
      },
      {
        name: '8ball',
        description: 'マジック8ボール（質問に答えます）',
        options: [
          {
            name: 'question',
            description: 'Yes/Noで答えられる質問',
            type: 'string',
            required: true,
          },
        ],
        responseType: ResponseType.STATIC_TEXT,
        staticText: '🎱 質問: {question}\n\n答え: {random("はい、間違いありません", "確実です", "間違いなくそうです", "多分そうでしょう", "見込みあり", "微妙です", "もう一度聞いて", "今は答えられません", "見通しは良くない", "非常に疑わしい")}',
        autoGeneratedCode: true,
      },
    ],
    tags: ['ゲーム', '娯楽', 'API不要', 'ランダム'],
    difficulty: 'beginner',
    setupInstructions: 'API不要！完全にローカルで動作します。',
  },

  // 8. 挨拶ボット（API不要、シンプル）
  {
    id: 'simple-greeting',
    name: '👋 シンプル挨拶ボット',
    description: '基本的な挨拶コマンド。Discord Botの基礎を学ぶのに最適。',
    category: 'utility',
    icon: '👋',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: 'シンプルな挨拶ボット',
    },
    apiProfiles: [],
    commands: [
      {
        name: 'hello',
        description: '挨拶をします',
        options: [],
        responseType: ResponseType.STATIC_TEXT,
        staticText: 'こんにちは！👋 私はDiscord Botです！',
        autoGeneratedCode: true,
      },
      {
        name: 'ping',
        description: 'Pong!と返します',
        options: [],
        responseType: ResponseType.STATIC_TEXT,
        staticText: 'Pong! 🏓',
        autoGeneratedCode: true,
      },
      {
        name: 'greet',
        description: '指定したユーザーに挨拶します',
        options: [
          {
            name: 'user',
            description: '挨拶するユーザー',
            type: 'user',
            required: true,
          },
        ],
        responseType: ResponseType.STATIC_TEXT,
        staticText: 'こんにちは、{user}さん！ 👋',
        autoGeneratedCode: true,
      },
    ],
    tags: ['初心者', '挨拶', 'シンプル', 'API不要'],
    difficulty: 'beginner',
    setupInstructions: 'API不要！Discord Botの基本を学べる最もシンプルなテンプレートです。',
  },

  // 9. 空のテンプレート（カスタム用）
  {
    id: 'blank',
    name: '📝 空のテンプレート',
    description: 'ゼロから自分でボットを作成します。完全にカスタマイズ可能です。',
    category: 'custom',
    icon: '📝',
    defaultBotConfig: {
      deploymentType: BotDeploymentType.INTERACTIONS_ENDPOINT,
      description: '',
    },
    apiProfiles: [],
    commands: [],
    tags: ['カスタム', '空', '自由'],
    difficulty: 'beginner',
    setupInstructions: '自由にコマンドとAPIを追加してください。',
  },
];

/**
 * テンプレートIDからテンプレートを取得
 */
export function getTemplateById(id: string): BotTemplate | undefined {
  return BOT_TEMPLATES.find(template => template.id === id);
}

/**
 * カテゴリでテンプレートをフィルタリング
 */
export function getTemplatesByCategory(category: BotTemplate['category']): BotTemplate[] {
  return BOT_TEMPLATES.filter(template => template.category === category);
}

/**
 * 難易度でテンプレートをフィルタリング
 */
export function getTemplatesByDifficulty(difficulty: BotTemplate['difficulty']): BotTemplate[] {
  return BOT_TEMPLATES.filter(template => template.difficulty === difficulty);
}

/**
 * テンプレートからプロジェクト設定を生成
 */
export function createProjectConfigFromTemplate(
  template: BotTemplate,
  overrides: {
    repositoryName: string;
    botName: string;
    userId: string;
    repositoryDescription?: string;
    isPrivate?: boolean;
  }
) {
  // コマンドにIDを付与
  const commandsWithIds = template.commands.map((cmd, index) => ({
    ...cmd,
    id: `${template.id}-cmd-${index}`,
  }));

  return {
    repository: {
      name: overrides.repositoryName,
      branch: 'main',
      description: overrides.repositoryDescription || template.description,
      isPrivate: overrides.isPrivate ?? true,
    },
    botConfig: {
      name: overrides.botName,
      description: template.defaultBotConfig.description || template.description,
      deploymentType: template.defaultBotConfig.deploymentType || BotDeploymentType.INTERACTIONS_ENDPOINT,
    },
    apiProfiles: template.apiProfiles,
    commands: commandsWithIds,
  };
}
